import sequelize from '../config/database.js';
import Hero from '../models/Hero.js';
import dotenv from 'dotenv';

dotenv.config();

const herois = [
    {
    nome: 'Batman',
    gif_entrada: '/images/batman/entrada.gif',
    gif_ataque: '/images/batman/luta.gif',
    gif_saida: '/images/batman/saida.gif',
    ataque1_nome: 'Soco preciso',
    ataque1_dano: 25, 
    ataque1_precisao: 90, 
    ataque2_nome: 'Batarangue explosivo',
    ataque2_dano: 35,
    ataque2_precisao: 80,
    ataque_especial_nome: 'Tática mestre',
    ataque_especial_dano: 55,
    ataque_especial_precisao: 95,
    defesa: 40,
    velocidade: 50,
    vida_base: 110
  },
  {
    nome: 'Coringa',
    gif_entrada: '/images/coringa/entrada.gif',
    gif_ataque: '/images/coringa/luta.gif',
    gif_saida: '/images/coringa/saida.gif',
    ataque1_nome: 'Tiro surpresa',
    ataque1_dano: 20,
    ataque1_precisao: 85,
    ataque2_nome: 'Piada mortal',
    ataque2_dano: 30,
    ataque2_precisao: 70,
    ataque_especial_nome: 'Caos absoluto',
    ataque_especial_dano: 60,
    ataque_especial_precisao: 80,
    defesa: 20,
    velocidade: 45,
    vida_base: 90
  },
  {
    nome: 'Superman',
    gif_entrada: '/images/superman/entrada.gif',
    gif_ataque: '/images/superman/luta.gif',
    gif_saida: '/images/superman/saida.gif',
    ataque1_nome: 'Soco supersônico',
    ataque1_dano: 45,
    ataque1_precisao: 95,
    ataque2_nome: 'Visão de calor',
    ataque2_dano: 55,
    ataque2_precisao: 90,
    ataque_especial_nome: 'Voo devastador',
    ataque_especial_dano: 85,
    ataque_especial_precisao: 95,
    defesa: 60,
    velocidade: 80,
    vida_base: 200
  },
  {
    nome: 'Homem-Aranha',
    gif_entrada: '/images/spiderman/entrada.gif',
    gif_ataque: '/images/spiderman/luta.gif',
    gif_saida: '/images/spiderman/saida.gif',
    ataque1_nome: 'Teia impactante',
    ataque1_dano: 30,
    ataque1_precisao: 95,
    ataque2_nome: 'Vai-Teia!',
    ataque2_dano: 45,
    ataque2_precisao: 100,
    ataque_especial_nome: 'Amigão da Vizinhança',
    ataque_especial_dano: 65,
    ataque_especial_precisao: 90,
    defesa: 35,
    velocidade: 85, 
    vida_base: 120
  },
  {
    nome: 'Thanos',
    gif_entrada: '/images/thanos/entrada.gif',
    gif_ataque: '/images/thanos/luta.gif',
    gif_saida: '/images/thanos/saida.gif',
    ataque1_nome: 'Punho de titã',
    ataque1_dano: 50,
    ataque1_precisao: 85,
    ataque2_nome: 'Raio cósmico',
    ataque2_dano: 60,
    ataque2_precisao: 80,
    ataque_especial_nome: 'Estalo cósmico',
    ataque_especial_dano: 95,
    ataque_especial_precisao: 75,
    defesa: 70,
    velocidade: 40,
    vida_base: 210
  },
  {
    nome: 'Wanda Maximoff',
    gif_entrada: '/images/scarletwitch/entrada.gif',
    gif_ataque: '/images/scarletwitch/luta.gif',
    gif_saida: '/images/scarletwitch/saida.gif',
    ataque1_nome: 'Bola de caos',
    ataque1_dano: 35,
    ataque1_precisao: 90,
    ataque2_nome: 'Manipulação de realidade',
    ataque2_dano: 45,
    ataque2_precisao: 85,
    ataque_especial_nome: 'Hex definitivo',
    ataque_especial_dano: 80,
    ataque_especial_precisao: 70,
    defesa: 30,
    velocidade: 50,
    vida_base: 100
  },
  {
    nome: 'Omni-Man',
    gif_entrada: '/images/omniman/entrada.gif',
    gif_ataque: '/images/omniman/luta.gif',
    gif_saida: '/images/omniman/saida.gif',
    ataque1_nome: 'Impacto viltrumita',
    ataque1_dano: 55,
    ataque1_precisao: 90,
    ataque2_nome: 'Voo supersônico',
    ataque2_dano: 45,
    ataque2_precisao: 95,
    ataque_especial_nome: 'Fúria conquistadora',
    ataque_especial_dano: 90,
    ataque_especial_precisao: 85,
    defesa: 65,
    velocidade: 75,
    vida_base: 190
  },
  {
    nome: 'Homelander',
    gif_entrada: '/images/homelander/entrada.gif',
    gif_ataque: '/images/homelander/luta.gif',
    gif_saida: '/images/homelander/saida.gif',
    ataque1_nome: 'Raio laser',
    ataque1_dano: 40,
    ataque1_precisao: 85,
    ataque2_nome: 'Soco brutal',
    ataque2_dano: 35,
    ataque2_precisao: 80,
    ataque_especial_nome: 'Ataque psicótico',
    ataque_especial_dano: 70,
    ataque_especial_precisao: 75,
    defesa: 45,
    velocidade: 65,
    vida_base: 160
  },
  {
    nome: 'Goku',
    universo: 'Dragon Ball',
    gif_entrada: '/images/goku/entrada.gif',
    gif_ataque: '/images/goku/luta.gif',
    gif_saida: '/images/goku/saida.gif',
    ataque1_nome: 'Ataque de KI',
    ataque1_dano: 60,
    ataque1_precisao: 85,
    ataque2_nome: 'Kamehameha',
    ataque2_dano: 40,
    ataque2_precisao: 95,
    ataque_especial_nome: 'Genki Dama',
    ataque_especial_dano: 100,
    ataque_especial_precisao: 80,
    defesa: 55,
    velocidade: 90,
    vida_base: 260
  },
  {
    nome: 'Vegeta',
    universo: 'Dragon Ball',
    gif_entrada: '/images/vegeta/entrada.gif',
    gif_ataque: '/images/vegeta/luta.gif',
    gif_saida: '/images/vegeta/saida.gif',
    ataque1_nome: 'Final Flash',
    ataque1_dano: 65,
    ataque1_precisao: 80,
    ataque2_nome: 'Galick Gun',
    ataque2_dano: 50,
    ataque2_precisao: 85,
    ataque_especial_nome: 'Big Bang Attack',
    ataque_especial_dano: 95,
    ataque_especial_precisao: 75,
    defesa: 50,
    velocidade: 85,
    vida_base: 260
  },
  {
    nome: 'Wolverine',
    universo: 'X-Men',
    gif_entrada: '/images/wolverine/entrada.gif',
    gif_ataque: '/images/wolverine/luta.gif',
    gif_saida: '/images/wolverine/saida.gif',
    ataque1_nome: 'Garras de Adamantium',
    ataque1_dano: 45,
    ataque1_precisao: 90,
    ataque2_nome: 'Fúria Berserker',
    ataque2_dano: 55,
    ataque2_precisao: 75,
    ataque_especial_nome: 'Ataque Frenético',
    ataque_especial_dano: 80,
    ataque_especial_precisao: 70,
    defesa: 60,
    velocidade: 70,
    vida_base: 200
  },
  {
    nome: 'Magneto',
    universo: 'X-Men',
    gif_entrada: '/images/magneto/entrada.gif',
    gif_ataque: '/images/magneto/luta.gif',
    gif_saida: '/images/magneto/saida.gif',
    ataque1_nome: 'Campo Magnético',
    ataque1_dano: 40,
    ataque1_precisao: 90,
    ataque2_nome: 'Chuva de Metais',
    ataque2_dano: 55,
    ataque2_precisao: 85,
    ataque_especial_nome: 'Inversão Polar',
    ataque_especial_dano: 75,
    ataque_especial_precisao: 80,
    defesa: 65,
    velocidade: 60,
    vida_base: 150
  },
  {
    nome: 'Kratos',
    universo: 'God of War',
    gif_entrada: '/images/kratos/entrada.gif',
    gif_ataque: '/images/kratos/luta.gif',
    gif_saida: '/images/kratos/saida.gif',
    ataque1_nome: 'Lâmina do Caos',
    ataque1_dano: 50,
    ataque1_precisao: 85,
    ataque2_nome: 'Fúria Espartana',
    ataque2_dano: 60,
    ataque2_precisao: 75,
    ataque_especial_nome: 'Ira dos Deuses',
    ataque_especial_dano: 90,
    ataque_especial_precisao: 80,
    defesa: 55,
    velocidade: 65,
    vida_base: 200
  },
  {
    nome: 'Sailor Moon',
    universo: 'Sailor Moon',
    gif_entrada: '/images/sailormoon/entrada.gif',
    gif_ataque: '/images/sailormoon/luta.gif',
    gif_saida: '/images/sailormoon/saida.gif',
    ataque1_nome: 'Moon Tiara Action',
    ataque1_dano: 35,
    ataque1_precisao: 95,
    ataque2_nome: 'Moon Healing Escalation',
    ataque2_dano: 45,
    ataque2_precisao: 85,
    ataque_especial_nome: 'Moon Princess Halation',
    ataque_especial_dano: 70,
    ataque_especial_precisao: 90,
    defesa: 40,
    velocidade: 75,
    vida_base: 160
  },
  {
    nome: 'Saitama',
    universo: 'One Punch Man',
    gif_entrada: '/images/saitama/entrada.gif',
    gif_ataque: '/images/saitama/luta.gif',
    gif_saida: '/images/saitama/saida.gif',
    ataque1_nome: 'Sério Soco',
    ataque1_dano: 80,
    ataque1_precisao: 99,
    ataque2_nome: 'Sério Soco Consecutivo',
    ataque2_dano: 65,
    ataque2_precisao: 95,
    ataque_especial_nome: 'SÉRIO SOCO FINAL',
    ataque_especial_dano: 150,
    ataque_especial_precisao: 100,
    defesa: 80,
    velocidade: 85,
    vida_base: 250 
  },
  {
    nome: 'Levi Ackerman',
    universo: 'Attack on Titan',
    gif_entrada: '/images/levi/entrada.gif',
    gif_ataque: '/images/levi/luta.gif',
    gif_saida: '/images/levi/saida.gif',
    ataque1_nome: 'Manequipulação 3D',
    ataque1_dano: 40,
    ataque1_precisao: 100,
    ataque2_nome: 'Ataque Veloz',
    ataque2_dano: 45,
    ataque2_precisao: 95,
    ataque_especial_nome: 'Técnica Ackerman',
    ataque_especial_dano: 70,
    ataque_especial_precisao: 98,
    defesa: 35,
    velocidade: 90,
    vida_base: 110
  },
  {
    nome: 'Geralt de Rívia',
    universo: 'The Witcher',
    gif_entrada: '/images/geralt/entrada.gif',
    gif_ataque: '/images/geralt/luta.gif',
    gif_saida: '/images/geralt/saida.gif',
    ataque1_nome: 'Ataque de Prata',
    ataque1_dano: 45,
    ataque1_precisao: 85,
    ataque2_nome: 'Sinais Witcher',
    ataque2_dano: 35,
    ataque2_precisao: 90,
    ataque_especial_nome: 'Fúria do Lobo',
    ataque_especial_dano: 75,
    ataque_especial_precisao: 80,
    defesa: 50,
    velocidade: 70,
    vida_base: 160 
  },
  {
    nome: 'All Might',
    universo: 'My Hero Academia',
    gif_entrada: '/images/allmight/entrada.gif',
    gif_ataque: '/images/allmight/luta.gif',
    gif_saida: '/images/allmight/saida.gif',
    ataque1_nome: 'Texas Smash',
    ataque1_dano: 55,
    ataque1_precisao: 85,
    ataque2_nome: 'United States of Smash',
    ataque2_dano: 70,
    ataque2_precisao: 80,
    ataque_especial_nome: 'Plus Ultra Smash',
    ataque_especial_dano: 95,
    ataque_especial_precisao: 75,
    defesa: 60,
    velocidade: 75,
    vida_base: 180
  },
  {
    nome: 'Darth Vader',
    universo: 'Star Wars',
    gif_entrada: '/images/darthvader/entrada.gif',
    gif_ataque: '/images/darthvader/luta.gif',
    gif_saida: '/images/darthvader/saida.gif',
    ataque1_nome: 'Estrangulamento da Força',
    ataque1_dano: 40,
    ataque1_precisao: 90,
    ataque2_nome: 'Sabre de Luz',
    ataque2_dano: 55,
    ataque2_precisao: 85,
    ataque_especial_nome: 'Poder do Lado Sombrio',
    ataque_especial_dano: 80,
    ataque_especial_precisao: 80,
    defesa: 65,
    velocidade: 60,
    vida_base: 170
  },
  {
    nome: 'Mestre dos Magos',
    universo: 'Adventure Time',
    gif_entrada: '/images/magodesmagos/entrada.gif',
    gif_ataque: '/images/magodesmagos/luta.gif',
    gif_saida: '/images/magodesmagos/saida.gif',
    ataque1_nome: 'Feitiço Elemental',
    ataque1_dano: 35,
    ataque1_precisao: 90,
    ataque2_nome: 'Bola de Energia',
    ataque2_dano: 45,
    ataque2_precisao: 85,
    ataque_especial_nome: 'Magia do Caos',
    ataque_especial_dano: 70,
    ataque_especial_precisao: 75,
    defesa: 40,
    velocidade: 50,
    vida_base: 150
  }
];

const seedHeroes = async () => {
  try {
    await sequelize.sync({ force: true });
    await Hero.bulkCreate(herois);
    console.log('✅ Heróis inseridos com sucesso!');
    process.exit();
  } catch (error) {
    console.error('❌ Erro ao inserir heróis:', error);
    process.exit(1);
  }
};

seedHeroes();
